// ESLint flat config (v10).
// Biome handles general JS/TS lint + formatting; ESLint adds the things biome
// CAN'T: type-aware rules (it has no type information) across the whole repo,
// plus the React-specific rules for the frontend.
//
// React plugin: @eslint-react/eslint-plugin (the modern rewrite by rel1cx).
import css from "@eslint/css";
import js from "@eslint/js";
import globals from "globals";
import html from "@html-eslint/eslint-plugin";
import eslintReact from "@eslint-react/eslint-plugin";
import jsxA11yPlugin from "eslint-plugin-jsx-a11y";
import reactHooksPlugin from "eslint-plugin-react-hooks";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    // prompt-kit/** and ui/** are vendored shadcn/prompt-kit components tracked
    // from upstream (and already excluded from biome). We re-sync them, so our
    // house rules shouldn't fight upstream's conventions.
    ignores: [
      "dist/**",
      "node_modules/**",
      ".claude/**",
      "web/v3/components/prompt-kit/**",
      "web/v3/components/ui/**",
      "**/*.gen.css", // generated by the tailwind build — not hand-authored
    ],
  },
  {
    // Base: type-aware TypeScript + general correctness for the WHOLE codebase —
    // the daemon backend (src/) and the frontend (web/). The type-checked rules
    // (no-floating-promises, no-misused-promises, no-unsafe-*, await-thenable, …)
    // are exactly what biome can't provide, and the async-heavy backend is where
    // they earn their keep most.
    files: ["app/**/*.ts", "shared/**/*.ts", "scripts/**/*.ts", "tests/**/*.ts", "web/**/*.{ts,tsx}"],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommendedTypeChecked,
      tseslint.configs.stylisticTypeChecked,
    ],
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
        ecmaFeatures: { jsx: true },
      },
    },
    rules: {
      // Biome already enforces these general (non-type-aware) rules — it has
      // `noEmptyBlockStatements: error` and `noExplicitAny: error`. eslint's job
      // here is the TYPE-AWARE rules biome can't do, so don't double-enforce.
      "no-empty": "off",
      "@typescript-eslint/no-empty-function": "off",
      "@typescript-eslint/no-explicit-any": "off",
      // require-await ≈ biome's `useAwait` (which the codebase already
      // biome-ignores for intentionally-async-by-contract fns). Biome's domain.
      "@typescript-eslint/require-await": "off",
      // Passing an async fn to a void-arg slot (setInterval/setTimeout/process.on)
      // is the standard fire-and-forget timer/handler pattern; wrapping every one
      // in `void (async()=>{})()` is noise. Still enforced for promise-returning
      // values, properties, and JSX attribute handlers (the web onClick case).
      "@typescript-eslint/no-misused-promises": [
        "error",
        { checksVoidReturn: { arguments: false } },
      ],
      // A leading underscore marks a deliberately-unused binding.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" },
      ],
      // `??` for objects/numbers (where `||` eats 0 / a valid empty result);
      // `||` stays allowed for string/boolean operands (empty-skip is idiomatic).
      "@typescript-eslint/prefer-nullish-coalescing": [
        "error",
        { ignorePrimitives: { string: true, boolean: true } },
      ],
    },
  },
  {
    // React-specific rules — web/ only (the backend has no JSX).
    files: ["web/**/*.{ts,tsx}"],
    extends: [eslintReact.configs["recommended-typescript"]],
    plugins: {
      "react-hooks": reactHooksPlugin,
      "jsx-a11y": jsxA11yPlugin,
    },
    rules: {
      ...reactHooksPlugin.configs["recommended-latest"].rules,
      ...jsxA11yPlugin.flatConfigs.strict.rules,
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "error",
      // Our toggle rows nest the label text one level below the <input>.
      "jsx-a11y/label-has-associated-control": ["error", { depth: 3 }],
      // Biome already owns noArrayIndexKey; don't double-enforce here.
      "@eslint-react/no-array-index-key": "off",
      // React-Compiler-era rule; we don't run the Compiler and every flagged use
      // is a legitimate effect→state sync, not the derive-in-render anti-pattern.
      "react-hooks/set-state-in-effect": "off",
      "@eslint-react/set-state-in-effect": "off",
    },
  },
  {
    // Test files: bun:test's matcher types under-declare Promise returns —
    // `await expect(p).rejects.toThrow()` is a genuine awaitable typed as a
    // non-thenable, so await-thenable misfires (removing the await would silently
    // break the assertion). Async test bodies without await are also conventional.
    files: ["**/*.test.{ts,tsx}", "**/__tests__/**/*.{ts,tsx}"],
    rules: {
      "@typescript-eslint/await-thenable": "off",
      "@typescript-eslint/require-await": "off",
    },
  },
  {
    // Plain JS config/tooling files (e.g. this file). No TS project, so no
    // type-aware rules — just the JS recommended set.
    files: ["**/*.{js,mjs,cjs}"],
    extends: [js.configs.recommended],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: { ...globals.node },
    },
  },
  {
    // HTML entry shells (the SPA mount points). Structural HTML linting.
    ...html.configs["flat/recommended"],
    files: ["web/**/*.html"],
    rules: {
      ...html.configs["flat/recommended"].rules,
      // `<meta name="theme-color">` is an intentional progressive enhancement
      // (mobile address-bar tint); baseline gating is too strict for an internal
      // dashboard targeting known modern browsers.
      "@html-eslint/use-baseline": "off",
    },
  },
  {
    // Hand-written CSS (the *.gen.css tailwind output is ignored above).
    files: ["**/*.css"],
    plugins: { css },
    language: "css/css",
    extends: [css.configs.recommended],
    rules: {
      // Tailwind v4 is CSS-first: `@theme`/`@apply`/`@variant` aren't standard
      // at-rules, and design tokens (`--color-*`, `--font-*`) are defined by
      // tailwind/daisyui at build time, not in-file — the generic CSS validator
      // can't resolve either, so these two misfire. The rest of css/recommended
      // (empty blocks, duplicate imports, syntax) still applies.
      "css/no-invalid-at-rules": "off",
      "css/no-invalid-properties": "off",
      // Same call as the HTML block: baseline gating is too strict for an
      // internal dashboard. `ui-monospace`, `word-break: break-word` etc. are
      // well-supported, intentional choices.
      "css/use-baseline": "off",
    },
  },
);
